employee/urls.py
from django.conf.urls import url
from . import views

app_name = 'employee'

urlpatterns = [

		url(r'^$', views.home, name = 'home'),

		url(r'^save_employee_by_csv/$', views.save_employee_by_csv, name = 'save_employee_by_csv'),

		url(r'^save_kpi_by_csv/$', views.save_kpi_by_csv, name = 'save_kpi_by_csv'),

		url(r'^save_rm_by_csv/$', views.save_rm_by_csv, name = 'save_rm_by_csv'),

		url(r'^save_assignkpi_by_csv/$', views.save_assignkpi_by_csv, name = 'save_assignkpi_by_csv'),

		url(r'^user_home/$', views.user_home, name = 'user_home'),

		url(r'^report_manager_home/$', views.report_manager_home, name = 'report_manager_home'),

		url(r'^hr_home/$', views.hr_home, name = 'hr_home'),
		
		url(r'^ceo_home/$', views.ceo_home, name = 'ceo_home'),

		url(r'^view_profile/$', views.view_profile, name = 'view_profile'),

		url(r'^team/(?P<emp_id>[0-9]+)/$', views.team, name='team'),

		url(r'^define_reviewers/(?P<emp_id>[0-9]+)/$', views.define_reviewers, name='define_reviewers'),

		url(r'^view_reviewers/(?P<emp_id>[0-9]+)/$', views.view_reviewers, name='view_reviewers'),

		url(r'^delete_reviewer/(?P<reviewer_id>[0-9]+)/$', views.delete_reviewer, name='delete_reviewer'),

		# url(r'^fill_kpi_form/(?P<emp_id>[0-9]+)/$', views.fill_kpi_form, name= 'fill_kpi_form'),

		# url(r'^fill_category_form/(?P<emp_id>[0-9]+)/$', views.fill_category_form, name= 'fill_category_form'),

		# url(r'^update_category_form/(?P<emp_id>[0-9]+)/$', views.update_category_form, name= 'update_category_form'),

		url(r'^save_category_form/(?P<emp_id>[0-9]+)/$', views.save_category_form, name= 'save_category_form'),

		url(r'^save_category_form_new/(?P<emp_id>[0-9]+)/$', views.save_category_form_new, name= 'save_category_form_new'),

		url(r'^employees_under_rm/(?P<emp_id>[0-9]+)/$', views.employees_under_rm, name= 'employees_under_rm'),

		url(r'^view_all_employees/(?P<emp_id>[0-9]+)/$', views.view_all_employees, name= 'view_all_employees'),

		url(r'^form_status/(?P<emp_id>[0-9]+)/$', views.form_status, name= 'form_status'),

		url(r'^form_status_next/(?P<emp_id>[0-9]+)/$', views.form_status_next, name= 'form_status_next'),
		# url(r'^view_category_form/(?P<emp_id>[0-9]+)/$', views.view_category_form, name= 'view_category_form'),

		url(r'^view_competency/(?P<emp_id>[0-9]+)/$', views.view_competency, name= 'view_competency'),

		url(r'^view_competency_result/(?P<emp_id>[0-9]+)/(?P<category_id>[0-9]+)/$', views.view_competency_result, name= 'view_competency_result'),

		url(r'^view_competency_result_previous/(?P<emp_id>[0-9]+)/(?P<category_id>[0-9]+)/$', views.view_competency_result_previous, name= 'view_competency_result_previous'),

		# url(r'^view_kpi_form/(?P<emp_id>[0-9]+)/$', views.view_kpi_form, name= 'view_kpi_form'),

		# url(r'^provide_feedback/(?P<emp_id>[0-9]+)/$', views.provide_feedback, name= 'provide_feedback'),

		url(r'^update_feedback/(?P<emp_id>[0-9]+)/$', views.update_feedback, name= 'update_feedback'),

		url(r'^view_feedback/(?P<emp_id>[0-9]+)/$', views.view_feedback, name= 'view_feedback'),

		# url(r'^team/$', views.team, name= 'team'),
		url(r'^get_rating/$', views.get_rating, name='get_rating'),

]

employee/models.py
#!/usr/bin/env python

# Python imports.
from __future__ import unicode_literals
import logging
import datetime
import os

# Django imports.
from django.contrib.auth.models import(
    BaseUserManager, AbstractBaseUser, PermissionsMixin)
from django.db import models
from django.utils import timezone
from django.contrib.auth.hashers import is_password_usable 
from django.core.exceptions import ValidationError
# Third Party Library imports


# local imports.
from configuration.models import *
from appraisal_system import constants

logger = logging.getLogger(__name__)


class MyUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        # username = self.model.normalize_username(username)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class EmployeeProfile(AbstractBaseUser, PermissionsMixin):
    emp_name = models.CharField(max_length=255, null=True,blank=True,verbose_name='Employee Name')
    emp_code = models.CharField(max_length=10, unique=True, blank=True,verbose_name='Employee Code')
    email = models.EmailField("Email", unique=True)
    password = models.CharField(max_length=100)
    role = models.CharField(max_length=40,choices=constants.ROLES,verbose_name='Role', null=True,blank=True)
    emp_level = models.ForeignKey(Level, verbose_name='Level', null=True,blank=True)
    emp_designation = models.ForeignKey(
        Designation, verbose_name='Designation', null=True,blank=True)
    emp_department = models.ForeignKey(
        Department, verbose_name='Department', null=True,blank=True)
    emp_stack = models.ForeignKey(Stack, verbose_name='Stack', null=True,blank=True)
    is_first_login = models.BooleanField('is first login', default=True)
    is_staff = models.BooleanField(
        'staff status',
        default=False,
        help_text=('Designates whether the user can log into this site.'),
    )
    is_active = models.BooleanField(
        'active',
        default=True,
        help_text=(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.emp_name

    def get_full_name(self):
        return self.emp_name

    def get_short_name(self):
        return self.emp_name

    def __unicode__(self):
        return self.emp_name or u''

    class Meta:
        verbose_name_plural = 'Employee Profiles'
        verbose_name = 'Employee Profile'
        ordering = ['emp_name']

class Reviewer(TimeStampedModel):
    employee = models.ForeignKey(
        EmployeeProfile, related_name='employee')
    reviewer = models.ForeignKey(
        EmployeeProfile, related_name='reviewer')
    is_rm_approved = models.BooleanField(default=False, verbose_name='Is Feedback Manager Apporved')
    is_hr_approved = models.BooleanField(default=False)

    class Meta:
        unique_together = ('employee','reviewer')
    def __str__(self):
        return self.reviewer.emp_name
        
class ReportingManager(TimeStampedModel):
    employee = models.ForeignKey(
        EmployeeProfile, related_name='rep_manager_parent', unique=True)
    report_manager = models.ForeignKey(
        EmployeeProfile, on_delete=models.CASCADE, limit_choices_to={'is_staff' : True},verbose_name='Reporting Manager')
    class Meta:
        verbose_name_plural = 'Reporting Managers'
        verbose_name = 'Reporting Manager'

    def __str__(self):
        return self.report_manager.emp_name
 
    def clean(self):
        super(ReportingManager, self).clean()
        if not (self.employee_id and self.report_manager_id):
            raise ValidationError("Please select any value for fields") 
        elif  (self.employee_id == self.report_manager_id):
            raise ValidationError("Employee and ReportingManager cannot be the same!")

class CategoryResult(TimeStampedModel):
    employee = models.ForeignKey(EmployeeProfile, verbose_name='employee')
    category = models.ForeignKey(Category, related_name='category_result')
    comments = models.TextField(blank=True, null=True)
    filled_by = models.ForeignKey(
        EmployeeProfile, related_name='category_filled_by') 
    class Meta:
        unique_together=('employee','category', 'filled_by')


class EmployeeFeedBack(TimeStampedModel):
    employee = models.OneToOneField(EmployeeProfile, verbose_name='employee')
    rm_rating = models.FloatField(default=0.0, null=True,blank=True)
    hr_rating = models.FloatField(default=0.0, null=True,blank=True)
    ceo_rating = models.FloatField(default=0.0, null=True,blank=True)
    rm_feedback = models.TextField(null=True,blank=True)
    hr_feedback = models.TextField(null=True,blank=True)
    ceo_feedback = models.TextField(null=True,blank=True)
    report_manager = models.ForeignKey(EmployeeProfile, related_name='report_manager',null=True,blank=True)
    hr = models.ForeignKey(EmployeeProfile, related_name='hr',null=True,blank=True)
    ceo = models.ForeignKey(EmployeeProfile,related_name='ceo',null=True,blank=True)
    hr_approved = models.BooleanField(default=False)
    ceo_approved = models.BooleanField(default=False)

employee/forms.py
from django import forms
from django.db.models import Q
from employee.models import *

from configuration.models import *

class ReviewerForm(forms.Form):
	empset = EmployeeProfile.objects.order_by()
	reviewer = forms.ModelMultipleChoiceField(queryset=empset, required=False, widget=forms.CheckboxSelectMultiple())
	# def __init__(self, user, *args, **kwargs):
	# 	import pdb;pdb.set_trace()
	# 	super(ReviewerForm, self).__init__(*args, **kwargs)
	# 	try:
	# 		rm = ReportingManager.objects.get(employee=user.id)
	# 		self.fields['reviewer'].queryset = EmployeeProfile.objects.exclude(Q(id=rm.report_manager.id)|Q(id=user.id)|Q(emp_name__icontains='admin'))			
	# 	except:
	# 		self.fields['reviewer'].queryset = EmployeeProfile.objects.exclude(Q(id=user.id)|Q(emp_name__icontains='admin'))

class CategoryForm(forms.Form):
	empset = EmployeeProfile.objects.order_by().distinct()
	category = forms.CharField(widget=forms.HiddenInput(), label='category')
	comments = forms.CharField( widget=forms.Textarea(attrs={
						'placeholder': 'Comments','rows': 10,'cols': 80, 
					}),
					required=True)
class UpdateCategoryForm(forms.Form):
	category = forms.CharField(widget=forms.HiddenInput(), label='category')
	comments = forms.CharField(widget=forms.Textarea(attrs={
						'placeholder': 'Comments','rows': 10,'cols': 80, 
					}),
					required=True)	
	
class FeedBackForm(forms.Form):
	rating = forms.FloatField(required=False, max_value=5.0, min_value=0.0)
	feedback = forms.CharField(widget=forms.Textarea(attrs={
						'placeholder': 'Feedback','rows': 10,'cols': 80, 
					}),
					required=True)

class HRFeedBackForm(forms.Form):
	rating = forms.FloatField(required=False, max_value=5.0, min_value=0.0)
	feedback = forms.CharField(widget=forms.Textarea(attrs={
						'placeholder': 'Feedback','rows': 10,'cols': 80, 
					}),
					required=False)
	hr_approved = forms.BooleanField(required=True)

class CEOFeedBackForm(forms.Form):
	rating = forms.FloatField(required=False, max_value=5.0, min_value=0.0)
	feedback = forms.CharField(widget=forms.Textarea(attrs={
						'placeholder': 'Feedback','rows': 10,'cols': 80, 
					}),
					required=False)
	ceo_approved = forms.BooleanField(required=True)


class UpdateFeedBackForm(forms.Form):
	rating = forms.FloatField(required=False,max_value=5.0, min_value=0.0)
	feedback = forms.CharField(widget=forms.Textarea(attrs={
						'placeholder': 'Feedback','rows': 10,'cols': 80, 
					}),
					required=True)

class UpdateHRFeedBackForm(forms.Form):
	rating = forms.FloatField(required=False,max_value=5.0, min_value=0.0)
	feedback = forms.CharField(widget=forms.Textarea(attrs={
						'placeholder': 'Feedback','rows': 10,'cols': 80, 
					}),
					required=False)
	hr_approved = forms.BooleanField(required=True)

class UpdateCEOFeedBackForm(forms.Form):
	rating = forms.FloatField(required=False,max_value=5.0, min_value=0.0)
	feedback = forms.CharField(widget=forms.Textarea(attrs={
						'placeholder': 'Feedback','rows': 10,'cols': 80, 
					}),
					required=False)
	ceo_approved = forms.BooleanField(required=True)

templates/employee/formstatus.html
{% extends "employee/base.html" %}
      {% block title %}
            PMS Site | All Members
      {% endblock %}
	{% block content %}
	<!DOCTYPE html>
<html>
<head>
<style>
table#t01 tr:nth-child(even) {
    background-color:  #DCDCDC	;
}
table#t01 tr:nth-child(odd) {
   background-color:#fff;
}
table#t01 th {
    background-color:#696969  ;
    color: black;
}
table#t01 td {
	text-align: center;
	height :50;
	width : 150;
	padding : 20;
}
table#t01 tr:hover{background-color:#c1c1c1}
</style>

</head>
<body>

<br /><br /><table id="t01" align="center" border='2'>
  <tr>
    <th>Reviewers</th>
    <th>Members</th>
  </tr>
	{% for def in defaulter_set %}
  <tr>
  	<td>{{def.emp_name}}</td>
    <td><a href="{% url 'employee:form_status_next' def.id %}" class = "addlink">Select</a></td>
  </tr>
  	{% endfor %}

</table>
</body>
</html>

{% endblock %}

templates/employee/hrhome.html
{% extends "employee/base.html" %}
      {% block title %}
            PMS Site | HR Home
      {% endblock %}
	{% block content %}
	<!DOCTYPE html>
<html>
<head>
<style >
  
#content-related {
    float: right;
    width: 260px;
    height: 350px;
    position: relative;
    bottom:400px;
    margin-right: -300px;
    background-color: #e2e2e2;
}

.alert {
    padding: 20px;
    background-color: #f44336;
    color: white;
    opacity: 1;
    transition: opacity 0.6s;
    margin-bottom: 15px;
}

.alert.success {background-color: #4CAF50;}
.alert.info {background-color: #2196F3;}
.alert.warning {background-color: #ff9800;}

.closebtn {
    margin-left: 15px;
    color: white;
    font-weight: bold;
    float: right;
    font-size: 22px;
    line-height: 20px;
    cursor: pointer;
    transition: 0.3s;
}

.closebtn:hover {
    color: black;
}

</style>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js">
  
</script> 
<script>
function ShowHide()
{
  var self_form_expired = "{{ self_form_expired }}"
  var team_form_active = "{{ team_form_active }}"
  var can_view_feedback = "{{ can_view_feedback }}"
  // $('#hi').html(self_form_expired );
  if (self_form_expired === 'True'){
    $('#app1 a, #app2 a, #app3 a').css('color','grey');
    $("#app1, #app2, #app3").click(function(e){
    e.preventDefault();});    
  }
  if (team_form_active === 'False'){
    $('#app4 a,').css('color','grey');
    $("#app4, ").click(function(e){
    e.preventDefault();});     
  }
  if (can_view_feedback === 'False'){
    $('#app7 a,').css('color','grey');
    $("#app7, ").click(function(e){
    e.preventDefault();});     
  }
}

$(document).ready(function(){

    // ShowHide();

});

</script>
<script type="text/javascript" src="/static/js/jquery.countdown.js"></script> 
</head>
<body class=" dashboard" data-admin-utc-offset="0">
  <div id="container">
    <div id="content" class="colMS">
    {% if message %}
      <div class="alert success">
      <span class="closebtn">&times;</span>  
       {{ message }} 
      </div>
    {% endif %}
    <h1>Appraisal Site</h1>
    <h3 align="right" class="countdown_timer" id="getting-started"></h3>
      <div id="content-main">
        <div class="home module">
          <table>
            <caption>
              Member
            </caption>
            <tbody>
            <tr id ='app1'>
              <th scope="row">
                Add Reviewers
              </th>
              <td>
                <a href="{%url 'employee:define_reviewers' user.id%}" class = "addlink">Select</a>
              </td>
            </tr>
            <tr id='app2'>
              <th scope="row">
                View Reviewers
              </th>
              <td>
                <a href="{%url 'employee:view_reviewers' user.id%}" class = "addlink">Select</a>
              </td>
            </tr>
            <tr id='app3'>
              <th scope="row">
                Self Appraisal
              </th>
              <td>
                
                <a href="{% url 'employee:save_category_form' user.id %}" class = "changelink">Select</a>
              </td>
            </tr>   
            <tr id='app4'>
              <th scope="row">
                Team Appraisal
              </th>
              <td>
                <a href="{% url 'employee:team' user.id %}" class = "addlink">Select</a>
              </td>
            </tr>
            <!-- <tr id='app7'>
              <th scope="row">
                View Feedback
              </th>
              <td>
                <a href="{% url 'employee:view_feedback' user.id %}" class = "addlink">Select</a>
              </td>
            </tr>          -->
          </tbody>
        </table><br />
        <table>
          <caption>
            Feedback Manager
          </caption>
          <tbody>
          <tr>
            <th scope="row">
              Reportees
            </th>
            <td>
              <a href="{% url 'employee:employees_under_rm' user.id %}" class = "addlink">Select</a>
            </td>
          </tr>         
        </tbody>
      </table><br />
        <table>
          <caption>
            HR
          </caption>
          <tbody>
          <tr>
            <th scope="row">
              All Members
            </th>
            <td>
              <a href="{% url 'employee:view_all_employees' user.id %}" class = "addlink">Select</a>
            </td>
          </tr>     
          <tr>
            <th scope="row">
              Defaulters
            </th>
            <td>
              <a href="{% url 'employee:form_status' user.id %}" class = "addlink">Select</a>
          </tr>
          <tr>
            <th scope="row">
              Rating Report
            </th>
            <td>
              <a href="{% url 'employee:get_rating' %}" class = "addlink">Download</a>
            </td>
          </tr>
          <tr>
            <th scope="row">
              Rating Report 2017
            </th>
            <td>
              <a href="{% url 'employee:get_rating' %}?year='2017'" class = "addlink">Download</a>
            </td>
          </tr>      
        </tbody>
      </table>
      </div>

      <div id="content-related">
        <div class="module" id="recent-actions-module">
          <h2>Notifications</h2>
          <ul style="list-style-type:square">
            <li>Last date to fill-up feedback of your team {{last_date3}}</li>
            <li>Last date to fill-up feedback form is {{last_date5}}</li>
          </ul>
        </div>
      </div>
      <br class="clear">
      
    </div>
  </div>
</body>
<script>
  var close = document.getElementsByClassName("closebtn");
  var i;

  for (i = 0; i < close.length; i++) {
      close[i].onclick = function(){
          var div = this.parentElement;
          div.style.opacity = "0";
          setTimeout(function(){ div.style.display = "none"; }, 600);
      }
  }

  $("#getting-started").countdown("{{ day_left }}", function(event) {
    $(this).text("Time left for submission: "+
      event.strftime('%D days %H:%M:%S')
    );
  });
</script>
</html>

{% endblock %}

templates/employee/report_manager_home.html
{% extends "employee/base.html" %}
      {% block title %}
            PMS Site | RM Home
      {% endblock %}
	{% block content %}
	<!DOCTYPE html>
<html>
<head>
<!-- /*<style>
table#t01 tr:nth-child(even) {
    background-color:  #DCDCDC	;
}
table#t01 tr:nth-child(odd) {
   background-color:#fff;
}
table#t01 th {
    background-color:#696969  ;
    color: black;
}
table#t01 td {
	text-align: center;
	height :50;
	width : 250;
	padding : 20;
}
table#t01 tr:hover{background-color:#c1c1c1}
</style>*/ -->
<style >
  
#content-related {
    float: right;
    width: 260px;
    height: 350px;
    position: relative;
    bottom:310px;
    margin-right: -300px;
    background-color: #e2e2e2;
}
.alert {
    padding: 20px;
    background-color: #f44336;
    color: white;
    opacity: 1;
    transition: opacity 0.6s;
    margin-bottom: 15px;
}

.alert.success {background-color: #4CAF50;}
.alert.info {background-color: #2196F3;}
.alert.warning {background-color: #ff9800;}

.closebtn {
    margin-left: 15px;
    color: white;
    font-weight: bold;
    float: right;
    font-size: 22px;
    line-height: 20px;
    cursor: pointer;
    transition: 0.3s;
}

.closebtn:hover {
    color: black;
}


.countdown_timer{
  color: red;
}
</style>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js">
  
</script> 
<script type="text/javascript" src="/static/js/jquery.countdown.js"></script> 
<script>
function ShowHide()
{
  var self_form_expired = "{{ self_form_expired }}"
  var team_form_active = "{{ team_form_active }}"
  var can_view_feedback = "{{ can_view_feedback }}"
  // $('#hi').html(self_form_expired );
  if (self_form_expired === 'True'){
    $('#app1 a, #app2 a, #app3 a').css('color','grey');
    $("#app1 a, #app2, #app3").click(function(e){
    e.preventDefault();});    
  }
  if (team_form_active === 'False'){
    $('#app4 a,').css('color','grey');
    $("#app4 a, ").click(function(e){
    e.preventDefault();});     
  }
  if (can_view_feedback === 'False'){
    $('#app7 a,').css('color','grey');
    $("#app7 a, ").click(function(e){
    e.preventDefault();});     
  }
}

$(document).ready(function(){

    // ShowHide();

});

</script>
</head>
<body>


<body class=" dashboard" data-admin-utc-offset="0">
  <div id="container">
    <div id="content" class="colMS">
    {% if message %}
      <div class="alert success">
      <span class="closebtn">&times;</span>  
       {{ message }} 
      </div>
    {% endif %}
        <h1>Appraisal Site</h1>
    <h3 align="right" class="countdown_timer" id="getting-started"></h3>

      <div id="content-main">
        <div class="home module">
          <table>
            <caption>
              Member
            </caption>
            <tbody>
            <tr id='app1'>
              <th scope="row">
                Add Reviewers
              </th>
              <td>
                <a href="{%url 'employee:define_reviewers' user.id%}" class = "addlink">Select</a>
              </td>
            </tr>
            <tr id='app2'>
              <th scope="row">
                View Reviewers
              </th>
              <td>
                <a href="{%url 'employee:view_reviewers' user.id%}" class = "addlink">Select</a>
              </td>
            </tr id='app3'>
            <tr>
              <th scope="row">
                Self Appraisal
              </th>
              <td>
                
                <a href="{% url 'employee:save_category_form' user.id %}" class = "changelink">Select</a>
              </td>
            </tr>   
            <tr id='app4'>
              <th scope="row">
                Team Appraisal
              </th>
              <td>
                <a href="{% url 'employee:team' user.id %}" class = "addlink">Select</a>
              </td>
            </tr>
            <!-- <tr id='app7'>
              <th scope="row">
                View Feedback
              </th>
              <td>
                <a href="{% url 'employee:view_feedback' user.id %}" class = "addlink">Select</a>
              </td>
            </tr>   -->       
          </tbody>
        </table><br />
        <table>
          <caption>
            Feedback Manager
          </caption>
          <tbody>
          <tr>
            <th scope="row">
              Reportees
            </th>
            <td>
              <a href="{% url 'employee:employees_under_rm' user.id %}" class = "addlink">Select</a>
            </td>
          </tr>         
        </tbody>
      </table>
      </div>

      <div id="content-related">
        <div class="module" id="recent-actions-module">
          <h2>Notifications</h2>
          <ul style="list-style-type:square">
            <li>Last date to fill-up feedback of your team {{last_date3}}</li>
            <li>Last date to fill-up feedback form is {{last_date5}}</li>
          </ul>
        </div>
      </div>
      <br class="clear">
      
    </div>
  </div>
</body>
<script>
  var close = document.getElementsByClassName("closebtn");
  var i;

  for (i = 0; i < close.length; i++) {
      close[i].onclick = function(){
          var div = this.parentElement;
          div.style.opacity = "0";
          setTimeout(function(){ div.style.display = "none"; }, 600);
      }
  }



  $("#getting-started").countdown("{{ day_left }}", function(event) {
    $(this).text("Time left for submission: "+
      event.strftime('%D days %H:%M:%S')
    );
  });
</script>
</html>

{% endblock %}

templates/employee/team.html
{% extends "employee/base.html" %}
      {% block title %}
            PMS Site | My Team
      {% endblock %}
	{% block content %}    
    {% if msg %}
      {{msg}}
    {% else %}

<!DOCTYPE html>
<html>
<head>
<style>
table#t01 tr:nth-child(even) {
    background-color:  #DCDCDC	;
}
table#t01 tr:nth-child(odd) {
   background-color:#fff;
}
table#t01 th {
    background-color:#696969  ;
    color: black;
}
table#t01 td {
	text-align: center;
	height :50;
	width : 150;
	padding : 5;
}

</style>
</head>
<body>
<br /><br /><p align="center">Fill up forms of below members:</p>
<table id="t01" align='center' border="2">

  <tr>
  <th>Member</th>
  <th>Appraisal Form</th>
  <th>Status</th>
  </tr>
  {% for emp in empset %}  
  <tr>
    <td>{{emp.employee.emp_name}}</td>
    <td><a href="{% url 'employee:save_category_form' emp.employee.id %}">Fill Category Form</a>
    </td>
    <td> 
    {% for result in categoryresult %}
        {% if result.employee.id == emp.employee.id %}
            {% if result.comments %}
             <p>&#x2714;</p>
            {% endif %}
        {% endif %}
    {% endfor %} 
    </td>   
  {% endfor %}
  </tr>
</table>
</body>
</html>

        {% endif %}

{% endblock %}

templates/employee/view_reviewer.html
{% extends "employee/base.html" %}
      {% block title %}
            PMS Site | View Reviewers
      {% endblock %}
	{% block content %}    
    {% if msg %}
      {{msg}}
    {% else %}

<!DOCTYPE html>
<html>
<head>
<style>
table#t01 tr:nth-child(even) {
    background-color:  #DCDCDC	;
}
table#t01 tr:nth-child(odd) {
   background-color:#fff;
}
table#t01 th {
    background-color:#696969  ;
    color: black;
    text-align: center;
}
table#t01 td {
	text-align: center;
	height :50;
	width : 250;
	padding : 10px;
  text-align: center;
}
</style>
</head>
<body>
<br /><br /><p align="center">You have added the below reviewers:</p>
<table id="t01" align='center' border="2">

  {% for emp in empset %}  
  <tr>
    <td>{{emp.reviewer.emp_name}}</td>
    <td><a href="{% url 'employee:delete_reviewer' emp.reviewer.id %}" onclick="return confirm('Are you sure you want to delete this?')">Delete</a></td>
  </tr>
  {% endfor %}
</table>
</body>
</html>

    {% endif %}

{% endblock %}